name: MacOS

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install depedencies using brew
      run: brew install pkgconfig glibmm libxml++ jack liblo libsndfile gtkmm3 eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl coreutils qt qtkeychain &&
           echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> /Users/runner/.bash_profile &&
           export LDFLAGS="-L/usr/local/opt/qt/lib" &&
           export CPPFLAGS="-I/usr/local/opt/qt/include" &&
           export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
    - name: Configure project
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DQT_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1
    - name: Build
      run: make
    - name: Create installer
      run: cpack
    - name: Publish installer
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: InstallDigitalStage.dmg
        tag: ${{ github.ref }}
        overwrite: true
      
