name: Ubuntu

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Installing dependencies
      run: sudo apt update &&
           sudo apt install --assume-yes git liblo-dev nodejs libcurl4-openssl-dev build-essential libasound2-dev libeigen3-dev libfftw3-dev libfftw3-double3 libfftw3-single3 libgsl-dev libjack-jackd2-dev libltc-dev libmatio-dev libsndfile1-dev libsamplerate0-dev libboost-all-dev libxml++2.6-dev libcpprest-dev nlohmann-json-dev qt5-default qttools5-dev qt5keychain-dev
    - name: Configure project
      run: mkdir -p build && 
           cd build && 
           cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: make
    - name: Create package
      run: cpack
    #- name: Publish installer
    #  uses: svenstaro/upload-release-action@v2.2.1
    #  with:
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    file: build/InstallDigitalStage.dmg
    #    tag: ${{ github.ref }}
    #    overwrite: true